### ISSUE TITLE
Unicode error with danish characters

### ISSUE THREAD

**Issue by chubby1968** [chubby1968/LecToCal#1]
Issue originally described here: https://github.com/Hanse00/LecToCal/issues/25

> Hi LecToCal smart people.
> 
> I have tried using this, many times, un-installing and reinstalling since this is the limit of my python knowledge.
> 
> I then went through the changed lectocal.py and found out the error:
> SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc6 in position 0: invalid continuation byte
> is connected to the letter "Æ" and the sign "!".
> 
> Without these, the script will run.
> But nothing happens.
> 
> I have no succes with any other fix. Can someone help?
> 
> Best
> Charlotte

**Comment by chubby1968** [comment]
This issue can be replicated by saving the lectio.py file with other text encoding than utf-8.

For @charlotdk and others that might encounter the issue:

**How to avoid the issue:**

Download the raw file lectio.py (from [here](https://github.com/chubby1968/LecToCal/blob/master/lectocal/lectio.py) rightclick `raw` in topright corner and choose "save link as.."). Then edit the text in the downloaded file instead of copy-pasting the file into a text editor that might alter the text encoding.

Alternatively use a text editor that support choosing/changing text encoding, e.g. Notepad++, and make sure the file is encoded as utf-8 after entering username and password.

**Comment by charlotdk** [comment]
hello chubby1968

Thank you for helping me. I have been trying to replace "Æ" with "&AE" since this was the fix I googled myself to. However, it didn't help.

I have done as you write here, saved the Lectio.py directly with the link.
then opened Notepad++ and opened the file
replaced the 2 text-strings with my username and password
changed the dot (Konverter til ANSI / Kod i ANSI) 
then saved the new personal Lectio.py in the python/Lib/sitepackages/LecTocal folder, replacing the file allready there.
The file begins with # in line 1 and ends with (empty) in line 287

I then run the script as before.

The good thing is that I no longer get a lot of errors and stuff, it runs until the end, and I think (maybe) that it does make a new calendar in my g-calender.
I have rerun the oauth and redone the save-as-ansi after-replace-string.
I even tried the other options (including UTF-8 and UTF-8-BOM etc) and with "refreshenv" in between aso.
I run the call directly in C: as in:

C:\>python -m lectocal.run 5xx teacher 29200xxxx

It finishes and then nothing...

I did at one point get an "color id error" which is from g-calendar when the Lectio cal already exists and has a color. I usually fix it by deleting or renaming the Lectio layer of my calendar, making room for the new Lectio-run.

However, still nothing.
So - basically the script and LecToCal works/runs all the way through with the setup as described, but nothing is written into my g-calendar.
Before the GDRP/password thing a did use LecToCal and it did write every class, no exception, into my calendar. The call was the same.
I did - because of the errors with the fix - do an entire "Pip uninstall" and then "pip install" a while ago, but it was a repeat of the "before process" (a write my own "How-to's" so I can repeat stuff I have done/learned but not memorized) so unless I somehow did it wrong, but in a way so the scrip can run, it is weird...!!!

Can anyone figure this out? I am perplexed! XD


Best Charlot
